version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install ansible boto3
    pre_build:
        commands:
            - ansible --version
            - ansible-galaxy install -r requirements.yml
    build:
        commands:
            - ansible-playbook -i inventory hello-world.yml ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ansible.pem
artifacts:
    files:
        - '**/*'