version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
            dotnet: latest
        commands:
            - echo "Installing prerequisites..."
            - codebuild-breakpoint
            - mkdir -p /ansible/vars
            - cp /ansible/vars/creds.yml /ansible/vars/creds.yml
            - cp /ansible/vars/vars.yml /ansible/vars/vars.yml
            - pip install ansible
            - pip install pywinrm
            - pip install awscli
            - wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            - sudo dpkg -i packages-microsoft-prod.deb
            - rm packages-microsoft-prod.deb
            - apt-get update
            - apt-get install -y powershell
    build:
        commands:
            - echo "Building project..."
            - aws ssm send-command --document-name "run_powershell_cmd" --targets "Key=instanceIds,Values=i-01c6648cb07692045" --region us-east-1 --comment "Running PowerShell script via SSM" --parameters '{}' --timeout-seconds 600
            - ansible-playbook -i inventory dcpromo.yml
    post_build:
        commands:
            - echo "Build completed..."