version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
            dotnet: latest
        commands:
            - echo "Installing prerequisites..."
            - pip install ansible
            - pip install pywinrm
    build:
        commands:
            - echo "Building project..."
            - ansible-playbook -i inventory dcpromo.yml
    post_build:
        commands:
            - echo "Build completed..."