version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install ansible
            - pip install pywinrm
    pre_build:
        commands:
            - echo "Installing dependencies..."
            - ansible --version
    build:
        commands:
            - echo "Building project..."
            - ansible-playbook -i inventory dcpromo.yml
    post_build:
        commands:
            - echo "Build completed..."