version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python3 -m pip install ansible
  build:
    commands:
      - ansible-playbook -i inventory hello-world.yml