version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
            dotnet: latest
        commands:
            - echo "Installing prerequistes..."
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            - pip install ansible
            - pip install pywinrm
            - apt-get update
            - apt-get install -y powershell
            - pwsh -Command "$PSVersionTable.PSVersion"
    pre_build:
        commands:
            - echo "Installing dependencies..."
            - ansible --version
    build:
        commands:
            - echo "Building project..."
            - pwsh -Command "/AnsibleWinRMconfig.ps1"
            - ansible-playbook -i inventory dcpromo.yml
    post_build:
        commands:
            - echo "Build completed..."