version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install ansible boto3
    pre_build:
        commands:
            - ansible --version
            - ansible-galaxy install -r requirements.yml
    build:
        commands:
            - ansible-playbook hello-world.yml
artifacts:
    files:
        - '**/*'